blank_issues_enabled: false
contact_links:
  - name: Slam Mirrorbot Channels
    url: https://t.me/SlamMirrorUpdates
    about: Updates Channels
  - name: Slam Mirrorbot Group
    url: https://t.me/SlamSupport
    about: Support Group
